/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.demo.petstore;

import com.demo.petstore.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "0.8.0";
	public String genVersion = "2.258.2";
	public String userAgent = "speakeasy-sdk/java 0.8.0 2.258.2 1.0.0 com.demo.petstore";
	
	
}